CREATE DATABASE login;
USE login;
CREATE TABLE users
(
    userID INT NOT NULL PRIMARY KEY,
    username VARCHAR(255) NOT NULL,
    pass VARCHAR(255) NOT NULL
);
ALTER TABLE users CHANGE userID userID INT(11) NOT NULL AUTO_INCREMENT;